DECLARE
    IS_GRANTED NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO IS_GRANTED
    FROM DBA_ROLE_PRIVS
    WHERE GRANTEE = '#[schema_user]'
        AND GRANTED_ROLE = 'CONNECT';

    IF IS_GRANTED = 0 THEN
        EXECUTE IMMEDIATE 'GRANT CONNECT TO #[schema_user]';
    END IF;
END;
